/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs'); const path = require('node:path');
const webpack = require('next/dist/compiled/webpack/webpack').webpack;
const origin = new URL(process.env.TABAYYUN_BACKEND_ORIGIN || 'http://localhost:3000');
if (!['localhost','127.0.0.1'].includes(origin.hostname) || origin.protocol !== 'http:' || origin.username || origin.password || origin.pathname !== '/' || origin.search || origin.hash) throw new Error('Only localhost HTTP origins are supported until backend authentication exists.');
const out = path.join(__dirname,'dist'); fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({manifest_version:3,name:'Tabayyun Research',version:'0.3.0',minimum_chrome_version:'116',permissions:['contextMenus','sidePanel','storage','activeTab'],host_permissions:[`${origin.origin}/*`],background:{service_worker:'worker.js'},action:{default_title:'Open Tabayyun'},side_panel:{default_path:'sidepanel.html'},icons:{16:'icon16.png',48:'icon48.png',128:'icon128.png'},content_security_policy:{extension_pages:"script-src 'self'; object-src 'self'"}},null,2));
fs.copyFileSync(path.join(__dirname,'sidepanel.html'),path.join(out,'sidepanel.html'));
fs.writeFileSync(path.join(out,'panel.css'),fs.readFileSync(path.join(__dirname,'../app/globals.css'),'utf8')+'\nmain{padding:20px;max-width:640px}nav,.actions{display:flex;flex-wrap:wrap;gap:8px}article{background:white;border:1px solid #dce2da;padding:14px;margin:14px 0;border-radius:10px}textarea,select{width:100%;max-width:100%}small{display:block}h1{font-size:30px}input[type=checkbox]{width:auto}blockquote{margin:10px 0;white-space:pre-wrap;overflow-wrap:anywhere}a,p{overflow-wrap:anywhere}');
// Generate local PNG icons with Node's zlib; no native image dependency.
const zlib = require('node:zlib');
function crc(b){let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function chunk(t,b){const name=Buffer.from(t),n=Buffer.alloc(4),check=Buffer.alloc(4);n.writeUInt32BE(b.length);check.writeUInt32BE(crc(Buffer.concat([name,b])));return Buffer.concat([n,name,b,check]);}
for(const size of [16,48,128]){const head=Buffer.alloc(13);head.writeUInt32BE(size);head.writeUInt32BE(size,4);head[8]=8;head[9]=2;const raw=Buffer.alloc(size*(size*3+1));for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=y*(size*3+1)+1+x*3;const light=(y>size*.2&&y<size*.32&&x>size*.18&&x<size*.82)||(x>size*.43&&x<size*.57&&y>size*.25&&y<size*.8);raw[i]=light?246:40;raw[i+1]=light?247:87;raw[i+2]=light?243:64;}fs.writeFileSync(path.join(out,`icon${size}.png`),Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',head),chunk('IDAT',zlib.deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]));}
webpack({mode:'production',entry:{panel:path.join(__dirname,'panel.tsx'),worker:path.join(__dirname,'worker.ts')},output:{path:out,filename:'[name].js'},resolve:{extensions:['.tsx','.ts','.js']},module:{rules:[{test:/\.tsx?$/,exclude:/node_modules/,use:path.join(__dirname,'loader.cjs')}]},plugins:[new webpack.DefinePlugin({BACKEND_ORIGIN:JSON.stringify(origin.origin)})],optimization:{minimize:false},devtool:false},(error,stats)=>{if(error||stats.hasErrors()){console.error(error||stats.toString({all:false,errors:true}));process.exitCode=1;}else console.log(`Extension built: ${out} (backend ${origin.origin})`);});
