import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { capture, current, exportNotebook, safeURL, type Capture } from '../lib/notebook';
import { claimTypes, type Claim, type AnalysisRun, type RetrievalRun } from '../lib/types';
import { request, backend } from './api';
function Reference({ url, title }: { url: string; title: string }) { const href = safeURL(url); return href ? <a href={href} target="_blank" rel="noreferrer">{title || href}</a> : <span>{title || 'Manual paste — no page reference'}</span>; }
function Panel() {
  const [items,setItems] = useState<Capture[]>([]), [active,setActive] = useState(''), [view,setView] = useState('Capture');
  const [error,setError] = useState(''), [status,setStatus] = useState(''), [busy,setBusy] = useState(false), [selected,setSelected] = useState<string[]>([]);
  const [previews,setPreviews] = useState<AnalysisRun[]>([]);
  const [excluded,setExcluded] = useState<string[]>([]);
  const live = useRef<Capture | undefined>(undefined), controller = useRef<AbortController | null>(null), writes = useRef(Promise.resolve());
  const c = items.find(x => x.id === active);
  useEffect(() => { live.current = c; },[c]);
  async function refresh() { const r = await chrome.runtime.sendMessage({ type: 'read' }); if (r.error) throw new Error(r.error); setItems(r.captures); setActive(id => id || r.captures[0]?.id || ''); }
  useEffect(() => { const listener = () => { void writes.current.then(refresh).catch(e => setError(String(e))); }; listener(); chrome.storage.onChanged.addListener(listener); return () => { chrome.storage.onChanged.removeListener(listener); controller.current?.abort(); }; }, []);
  function persist(next: Capture) {
    live.current = next; setItems(old => [...old.filter(x => x.id !== next.id),next]);
    const write = writes.current.then(async () => { const r = await chrome.runtime.sendMessage({ type: 'put', capture: next }); if (r.error) throw new Error(r.error); });
    writes.current = write.catch(e => { setError(String(e)); });
    return write;
  }
  function edit(patch: Partial<Capture>) { if (!c) return; if (patch.editedText !== undefined) controller.current?.abort(); void persist({ ...c,...patch, revision: patch.editedText !== undefined ? c.revision + 1 : c.revision }); }
  async function run(mode: 'extract' | 'retrieve' | 'analyze') {
    if (!c || !c.editedText.trim()) return;
    if(c.editedText.length>30000){setError('Shorten the edited text to 30,000 characters. The original selection is retained.');return;}
    controller.current?.abort(); const abort = new AbortController(); controller.current = abort;
    const base = structuredClone(c); setBusy(true); setError(''); setStatus('');
    const valid = (claim?: Claim) => !abort.signal.aborted && live.current?.id === base.id && live.current.revision === base.revision && (!claim || live.current.claims.some(x => x.id === claim.id && x.revision === claim.revision));
    try {
      await writes.current;
      if (mode === 'extract') {
        const result = await request<{ claims: Claim[]; model: string; promptVersion: string }>('extract', { text: base.editedText, projectId: 'extension', materialId: base.id, materialRevision: base.revision }, abort.signal, `${base.id}:${base.revision}:${crypto.randomUUID()}`);
        if (valid()) { await persist({ ...live.current!, claims: [...live.current!.claims,...result.claims], extraction: result }); setView('Investigation'); setStatus('Review extracted claims before selecting them.'); }
      } else {
        const claims = base.claims.filter(x => selected.includes(x.id)); if (!claims.length || claims.length > 5) throw new Error('Select one to five claims.');
        let completed = 0;
        for (const claim of claims) {
          try {
            if (claim.materialRevision !== base.revision) throw new Error('Claim is outdated. Review it against the edited capture.');
            const id = `${base.id}:${base.revision}:${claim.id}:${claim.revision}:${crypto.randomUUID()}`;
            if (mode === 'retrieve') { const r = await request<{ retrieval: RetrievalRun }>('retrieve',{ claim },abort.signal,id); if (valid(claim)) { await persist({ ...live.current!, retrievals: [...live.current!.retrievals,r.retrieval] }); completed++; } }
            else { const retrieval = [...base.retrievals].reverse().find(x => x.claimId === claim.id && current(base,claim,x)); if (!retrieval) throw new Error('Retrieve current evidence first.'); const r = await request<{ analysis: AnalysisRun }>('analyze',{ claim, passageIds: retrieval.passages.filter(x => !excluded.includes(`${retrieval.id}:${x.id}`)).map(x => x.id) },abort.signal,id); if (valid(claim)) { setPreviews(old => [...old,r.analysis]); completed++; } }
          } catch (e) { if (abort.signal.aborted) throw e; setError(String(e)); }
        }
        setStatus(`${completed} of ${claims.length} ${mode === 'retrieve' ? 'retrievals completed' : 'findings ready for review and saving'}.`);
      }
    } catch (e) { setError(abort.signal.aborted ? 'Canceled. Previous work is retained.' : String(e)); }
    finally { if (controller.current === abort) setBusy(false); }
  }
  function amend(claim: Claim, patch: Partial<Claim>) { if (!c) return; controller.current?.abort(); const next = { ...claim,...patch, revision: claim.revision + 1, materialRevision: c.revision }; next.start = c.editedText.indexOf(next.excerpt); next.end = next.start + next.excerpt.length; next.validationIssue = next.start < 0 || !next.excerpt || (next.quotation && !next.excerpt.includes(next.quotation)) ? 'Correct excerpt or quotation to match capture.' : ''; void persist({ ...c,claims: c.claims.map(x => x.id === claim.id ? next : x) }); }
  return <main><p className="eyebrow">TABAYYUN AI</p><h1>Research with evidence.</h1><p className="badge">Extension notebook — saved on this device.</p><nav aria-label="Primary views">{['Capture','Investigation','Notebook'].map(v => <button key={v} aria-pressed={view === v} onClick={() => setView(v)}>{v}</button>)}</nav>
    {error && <p role="alert" className="error">{error}</p>}{status && <p role="status">{status}</p>}{busy && <p role="status">Working… <button onClick={() => controller.current?.abort()}>Cancel</button></p>}
    <p>{items.filter(x => x.id !== active && !x.saved).length} other drafts queued. Opening another draft retains this work.</p>
    <label>Active capture<select value={active} onChange={e => { controller.current?.abort(); setActive(e.target.value); setSelected([]); }}>{items.map(x => <option key={x.id} value={x.id}>{x.title || x.editedText.slice(0,40) || 'Manual draft'}</option>)}</select></label>
    <button onClick={async () => { const next = capture(); await persist(next); setActive(next.id); setView('Capture'); }}>New manual paste</button>
    {c && view === 'Capture' && <section><h2>Capture</h2><Reference url={c.url} title={c.title}/><small>Captured {c.createdAt} · revision {c.revision}</small><p>This page is material being investigated, not approved evidence.</p>{c.editedText.length>30000 && <p role="alert">This selection exceeds 30,000 characters. Shorten the edited text before extraction or saving; the original remains intact.</p>}<label>Text<textarea dir="auto" maxLength={30000} value={c.editedText} onChange={e => edit({ editedText: e.target.value })}/></label><details><summary>Original selection</summary><p dir="auto">{c.originalText || 'Manually pasted draft'}</p></details><label>Personal note<textarea dir="auto" maxLength={10000} value={c.note} onChange={e => edit({ note: e.target.value })}/></label><div className="actions"><button disabled={busy || !c.editedText.trim()} onClick={() => run('extract')}>Extract claims</button><button disabled={!c.editedText.trim() || c.editedText.length>30000} onClick={async () => { await persist({ ...c,saved:true }); setStatus('Excerpt saved on this device.'); }}>Save excerpt</button></div><p>Selections do not leave this device until you request extraction or analysis. Unsupported pages and PDF viewers may require manual paste.</p></section>}
    {c && view === 'Investigation' && <section><h2>Review claims</h2><Reference url={c.url} title={c.title}/><button onClick={() => { if (!c.editedText.trim()) return; const excerpt = c.editedText.slice(0,10000); const claim: Claim = { id: crypto.randomUUID(), projectId:'extension',materialId:c.id,materialRevision:c.revision,revision:1,excerpt,start:0,end:excerpt.length,statement:'',type:claimTypes[4],quotation:'',speaker:'',reference:'',validationIssue:'',coverageNote:'Limited curated collection.' }; void persist({...c,claims:[...c.claims,claim]}); }}>Add claim manually</button>
      {!c.claims.length && <p>Extract claims or add one manually. Review wording, attribution and qualifications.</p>}
      {c.claims.map(claim => <article key={claim.id}><label><input type="checkbox" checked={selected.includes(claim.id)} disabled={!selected.includes(claim.id) && selected.length >= 5} onChange={e => setSelected(old => e.target.checked ? [...old,claim.id] : old.filter(x => x !== claim.id))}/> Select claim</label>{claim.materialRevision !== c.revision && <p>Outdated claim — review against current capture.</p>}{(['statement','excerpt','quotation','speaker','reference'] as const).map(field => <label key={field}>{field}<textarea dir="auto" maxLength={field === 'excerpt' ? 10000 : field === 'quotation' ? 4000 : field === 'statement' ? 2000 : 300} value={claim[field]} onChange={e => amend(claim,{[field]:e.target.value})}/></label>)}<label>Type<select value={claim.type} onChange={e => amend(claim,{type:e.target.value as Claim['type']})}>{claimTypes.map(t => <option key={t}>{t}</option>)}</select></label>{claim.validationIssue && <p role="alert">{claim.validationIssue}</p>}<button onClick={() => amend(claim,{})}>Confirm reviewed claim</button><p>{claim.coverageNote}</p>
        {c.retrievals.filter(r => r.claimId === claim.id).slice(-1).map(r => <div key={r.id}><h3>Retrieved evidence {current(c,claim,r) ? '' : '— outdated'}</h3><p>{r.coverage}</p><p>Collection: {r.collectionVersion}. Searched: {r.sourcesSearched.map(s => s.title).join(', ')}</p>{!r.passages.length && <p>Insufficient evidence in the searched collection.</p>}{r.passages.map(p => <article key={p.id}><label><input type="checkbox" checked={!excluded.includes(`${r.id}:${p.id}`)} onChange={e => { controller.current?.abort(); setExcluded(old => e.target.checked ? old.filter(x => x !== `${r.id}:${p.id}`) : [...old,`${r.id}:${p.id}`]); }}/> Include evidence in analysis</label><p>{p.method}</p><blockquote dir="auto">{p.text}</blockquote><Reference url={p.source.URL} title={`${p.source.title} · ${p.locator}`}/><p>{p.source.edition} {p.source.translator}</p><details><summary>Surrounding context</summary><p dir="auto">{p.surroundingContext || 'No surrounding context available.'}</p></details></article>)}</div>)}
      </article>)}<div className="actions"><button disabled={busy || !selected.length} onClick={() => run('retrieve')}>Retrieve evidence</button><button disabled={busy || !selected.length} onClick={() => run('analyze')}>Run analysis</button></div>
      {[...c.analyses,...previews.filter(r => r.materialId === c.id && !c.analyses.some(x => x.id === r.id))].map(r => <article key={r.id}><h3>AI analysis {c.claims.some(x => x.id === r.claimId && current(c,x,r)) ? '' : '— outdated'}</h3><p>Quotation: {r.quotation}</p><p>Reference: {r.reference}</p><p>Contextual support: {r.support}</p><p dir="auto">{r.explanation}</p>{r.evidence.map((e,i) => <div key={i}><blockquote dir="auto">{e.excerpt}</blockquote><Reference url={e.citationSnapshot.URL} title={`${e.citationSnapshot.title} · ${e.passageSnapshot.locator}`}/></div>)}<p>{r.limitations.join(' ')}</p><p>{r.unresolvedQuestions.join(' ')}</p><p>{r.nextStep}</p><small>{r.model} · {r.promptVersion} · {r.createdAt}</small>{!c.analyses.some(x => x.id === r.id) && <button disabled={!c.claims.some(x => x.id === r.claimId && current(c,x,r))} onClick={async () => { await persist({...c,saved:true,analyses:[...c.analyses,{...r,personalNote:c.note}]}); setStatus('Finding saved on this device.'); }}>Save finding</button>}</article>)}
    </section>}
    {view === 'Notebook' && <section><h2>Notebook</h2><p>Exports are user-provided research, not server-verified findings. Import into a chosen website project; there is no automatic synchronization.</p><a href={`${backend}/projects`} target="_blank" rel="noreferrer">Open projects to import</a><button onClick={() => { const url = URL.createObjectURL(new Blob([JSON.stringify(exportNotebook(items),null,2)],{type:'application/json'})); const a = document.createElement('a'); a.href=url; a.download='tabayyun-notebook-v1.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url),1000); }}>Export JSON</button>{!items.some(x => x.saved) && <p>No saved excerpts or findings yet.</p>}{items.filter(x => x.saved).map(x => <article key={x.id}><Reference url={x.url} title={x.title}/><p dir="auto">{x.editedText.slice(0,300)}</p><p>{x.analyses.length} saved findings</p><label>Personal note<textarea maxLength={10000} dir="auto" value={x.note} onChange={e => void persist({...x,note:e.target.value})}/></label><button onClick={() => { controller.current?.abort(); setActive(x.id); setView('Capture'); }}>Reopen</button><button onClick={async () => { if (!confirm('Delete this capture and its findings from this device?')) return; await writes.current; const r = await chrome.runtime.sendMessage({type:'delete',id:x.id}); if (r.error) setError(r.error); else { setItems(r.captures); if (active === x.id) setActive(''); } }}>Delete</button></article>)}</section>}
  </main>;
}
createRoot(document.getElementById('root')!).render(<Panel/>);
