'use client';
import { useState } from 'react';
import Link from 'next/link';
import { researchRequest } from '@/lib/research/client';
import type { ResearchProject } from '@/lib/research/types';
export function AddToResearch({ evidenceIds, claimId }: { evidenceIds: string[]; claimId: string }) {
  const [projects, setProjects] = useState<ResearchProject[]>([]), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  async function collect(id: string) { await researchRequest({ action: 'collect', projectId: id, evidenceIds, claimId }); setMessage('Evidence saved with its original version and finding.'); }
  return <div><button disabled={busy || !evidenceIds.length} className="secondary" onClick={async () => { setBusy(true); try { const d = await researchRequest(); setProjects(d.projects); setOpen(true); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }}>Add to research project</button>{open && <><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { const f = new FormData(e.currentTarget); await collect(String(f.get('project'))); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }}><label>Existing project<select name="project" required>{projects.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label><button disabled={busy || !projects.length}>Save selected evidence</button></form><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { const f = new FormData(e.currentTarget); const p = await researchRequest({ action: 'create', title: f.get('title'), question: f.get('question') }); await collect(p.id); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }}><label>New project title<input name="title" required maxLength={120} /></label><label>Research question<textarea name="question" required maxLength={2000} /></label><button disabled={busy}>Create and collect</button></form><Link href="/research">Open research workspace</Link></>}<p role="status">{message}</p>{message && <p><Link href="/account">Account / sign in</Link> · <Link href="/sources">Service availability</Link></p>}</div>;
}
