'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
type Book = { id: string; title: string; author: string; edition: string; release: string; commit: string; sourceUrl: string; metadataUrl: string; license: string; licenseUrl: string; attribution: string; approval: string; sourceReviewStatus: string; usagePermissionStatus: string; technicalStatus: string };
type Passage = { id: string; bookId: string; locator: string; pageMarker: string; originalText: string };
export function LibraryBrowser() {
  const supplied = useSearchParams().get('q')?.trim() ?? '';
  const [query, setQuery] = useState('الصلاة'), [books, setBooks] = useState<Book[]>([]), [passages, setPassages] = useState<Passage[]>([]), [selected, setSelected] = useState<Passage>(), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [matchType, setMatchType] = useState<'none' | 'exact' | 'near'>('none'), [searched, setSearched] = useState(false);
  async function load(url = '/api/library') { setBusy(true); setError(''); try { const response = await fetch(url, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Library unavailable.'); setBooks(data.books ?? (data.book ? [data.book] : [])); setPassages(data.passages ?? []); setMatchType(data.matchType ?? 'none'); setSearched(url.includes('?q=')); if (data.passages?.length === 1 && url.includes('passage=')) setSelected(data.passages[0]); } catch (e) { setError(e instanceof Error ? e.message : 'Library unavailable.'); } finally { setBusy(false); } }
  useEffect(() => { let active = true; const url = supplied ? `/api/library?q=${encodeURIComponent(supplied)}` : '/api/library'; void fetch(url, { cache: 'no-store' }).then(async response => { if (supplied) setQuery(supplied); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Library unavailable.'); if (active) { setBooks(data.books ?? []); setPassages(data.passages ?? []); setMatchType(data.matchType ?? 'none'); setSearched(Boolean(supplied)); } }).catch(error => { if (active) setError(error instanceof Error ? error.message : 'Library unavailable.'); }); return () => { active = false; }; }, [supplied]);
  const effectiveQuery = supplied && query === '\u0627\u0644\u0635\u0644\u0627\u0629' ? supplied : query;
  async function search(event: FormEvent) { event.preventDefault(); if (effectiveQuery.trim()) await load(`/api/library?q=${encodeURIComponent(effectiveQuery.trim())}`); }
  const book = books.find(item => item.id === selected?.bookId) ?? books[0];
  const searchStatus = searched && matchType === 'near' ? <p role="status">No literal quotation match was found. The passages below are bounded distinctive-token near matches for manual comparison.</p> : searched && matchType === 'none' ? <p role="status">No literal or bounded near match was found in the imported OpenITI book.</p> : null;
  return <>
    <p className="eyebrow">AUTHENTICATED SOURCE PREVIEW</p><h1>OpenITI local passage viewer</h1>
    <p>This corpus route works locally and does not depend on Turath. Imported books remain preview-only until scholarly source review, usage permission, and technical release checks all pass.</p>
    {searchStatus}
    {error && <p className="error" role="alert">{error} {error.toLowerCase().includes('sign in') && <a href="/account">Sign in</a>}</p>}
    <form className="panel" onSubmit={search}><label>Search the selected Arabic text<input dir="rtl" value={query} maxLength={300} onChange={e => setQuery(e.target.value)} /></label><button disabled={busy || !query.trim()}>{busy ? 'Searching…' : 'Search local corpus'}</button></form>
    {book && <section className="panel"><h2 dir="rtl">{book.title}</h2><p dir="rtl">{book.author}</p><p>{book.edition}</p><p><strong>Authenticated preview; not approved as public evidence</strong> · OpenITI {book.release} · commit <code>{book.commit}</code></p><dl><dt>Technical ingestion</dt><dd>{book.technicalStatus}</dd><dt>Scholarly source review</dt><dd>{book.sourceReviewStatus}</dd><dt>Usage permission</dt><dd>{book.usagePermissionStatus} · <a href={book.licenseUrl} target="_blank" rel="noreferrer">{book.license}</a></dd></dl><p>{book.attribution}</p><p><a href={book.sourceUrl} target="_blank" rel="noreferrer">Pinned original text</a> · <a href={book.metadataUrl} target="_blank" rel="noreferrer">Pinned metadata</a></p></section>}
    {!!passages.length && <section><h2>Matches</h2>{passages.map(p => <article className="panel" key={p.id}><small>{p.locator} · marker preserved: {p.pageMarker}</small><blockquote className="passage" dir="rtl">{p.originalText.length > 900 ? `${p.originalText.slice(0, 900)}…` : p.originalText}</blockquote><button className="secondary" onClick={() => { setSelected(p); void load(`/api/library?passage=${encodeURIComponent(p.id)}`); }}>Open passage</button></article>)}</section>}
    {selected && <aside className="panel research-detail" role="dialog" aria-modal="true" aria-label="Passage viewer"><button className="secondary" onClick={() => setSelected(undefined)}>Close</button><h2>{selected.locator}</h2><p>Original OpenITI mARkdown and <code>{selected.pageMarker}</code> marker are preserved.</p><blockquote className="passage" dir="rtl">{selected.originalText}</blockquote>{book && <p>{book.attribution} · {book.edition} · <a href={book.sourceUrl} target="_blank" rel="noreferrer">source</a></p>}</aside>}
  </>;
}
