"use client";
import { useEffect, useState } from 'react';
import { importedCaptures, saveNotebookImport, type ImportedCapture } from '@/lib/repository';
import { safeURL } from '@/lib/notebook';
export function NotebookImport({ projectId }: { projectId: string }) {
  const [items,setItems] = useState<ImportedCapture[]>([]),[message,setMessage] = useState(''),[busy,setBusy] = useState(false);
  useEffect(() => { let live = true; importedCaptures(projectId).then(x => { if(live)setItems(x); }).catch(e => { if(live)setMessage(String(e)); }); return () => {live=false;}; },[projectId]);
  return <section className="panel"><h2>Extension notebook</h2><p>Import saved excerpts and findings into this project. Imported records are user-provided research; citations and AI judgments are not server-verified or added to the curated collection.</p><label>Versioned notebook JSON<input type="file" accept="application/json,.json" disabled={busy} onChange={async e => { const file=e.target.files?.[0]; e.target.value=''; if(!file)return; setBusy(true); try { if(file.size>10000000)throw new Error('Notebook must be at most 10 MB.'); const count=await saveNotebookImport(projectId,JSON.parse(await file.text())); setItems(await importedCaptures(projectId)); setMessage(`Imported ${count} records into this project. Repeated imports update existing records without duplicates.`); }catch(error){setMessage(String(error));}finally{setBusy(false);} }}/></label><p role="status">{busy?'Importing…':message}</p>{items.map(c => <article key={c.id}><h3>{c.title || 'Research excerpt'}</h3>{safeURL(c.url) && <a href={safeURL(c.url)} target="_blank" rel="noreferrer">Original page</a>}<p>Captured {c.createdAt} · revision {c.revision} · user-provided</p><blockquote dir="auto">{c.editedText}</blockquote><details><summary>Original selection</summary><p dir="auto">{c.originalText}</p></details><p dir="auto">Personal note: {c.note}</p>{c.claims.map(claim => <p key={claim.id} dir="auto">Claim (revision {claim.revision}): {claim.statement}</p>)}{c.analyses.map(r => <details key={r.id}><summary>Imported AI analysis: {r.support}{r.materialRevision!==c.revision||!c.claims.some(x=>x.id===r.claimId&&x.revision===r.claimRevision)?' — outdated':''}</summary><p>Quotation: {r.quotation}</p><p>Reference: {r.reference}</p><p dir="auto">{r.explanation}</p><p>{r.retrievalSnapshot.coverage}</p><p>Collection: {r.collectionVersion}</p>{r.evidence.map((ev,i)=><div key={i}><blockquote dir="auto">{ev.excerpt}</blockquote><p>{ev.citationSnapshot.title} · {ev.passageSnapshot.locator}</p>{safeURL(ev.citationSnapshot.URL)&&<a href={safeURL(ev.citationSnapshot.URL)} target="_blank" rel="noreferrer">Source reference</a>}<details><summary>Passage snapshot and context</summary><p dir="auto">{ev.passageSnapshot.text}</p><p dir="auto">{ev.passageSnapshot.surroundingContext || 'Context unavailable.'}</p></details></div>)}<p>{r.limitations.join(' ')}</p><p>{r.personalNote}</p><small>{r.model} · {r.promptVersion} · {r.createdAt}</small></details>)}</article>)}</section>;
}
