'use client';
import { useEffect, useRef, useState } from 'react';

import { Workspace } from './workspace';
import { ensureVerificationProject } from '@/lib/repository';
import Link from 'next/link';
import { researchRequest, ResearchRequestError } from '@/lib/research/client';
import type { ResearchState, ResearchProject, ResearchEvidence, ResearchDocument, Statement, ResearchNote } from '@/lib/research/types';
export function Research() {
  const [projects, setProjects] = useState<ResearchProject[]>([]), [resources, setResources] = useState<{ id: string; title: string; language: string }[]>([]), [state, setState] = useState<ResearchState>(), [tab, setTab] = useState('Evidence'), [error, setError] = useState(''), [status, setStatus] = useState(''), [busy, setBusy] = useState(false), [selected, setSelected] = useState<string[]>([]), [detail, setDetail] = useState<ResearchEvidence>(), [filter, setFilter] = useState('');
  const guard = useRef(false);
  const [authRequired, setAuthRequired] = useState(false), [loading, setLoading] = useState(true);
  const [inputOpen, setInputOpen] = useState(false);
  async function load(id?: string) { if (id) { setState(await researchRequest(undefined, id)); setSelected([]); } else { const data = await researchRequest(); setProjects(data.projects); setResources(data.resources); } }
  useEffect(() => { void researchRequest().then(d => { setProjects(d.projects); setResources(d.resources); }).catch(e => { setAuthRequired(e instanceof ResearchRequestError && e.code === 'AUTH_REQUIRED'); setError(e.message); }).finally(() => setLoading(false)); }, []);
  async function run(action: () => Promise<void>) { if (guard.current) return false; guard.current = true; setBusy(true); setError(''); setStatus(''); try { await action(); setStatus('Saved.'); return true; } catch (e) { setError(String(e)); return false; } finally { guard.current = false; setBusy(false); } }
  async function mutate(body: Record<string, unknown>) { const data = await researchRequest({ ...body, projectId: state?.project.id }); setState(data); }
  if (authRequired) return <section className="legal-page"><p className="eyebrow">RESEARCH WORKSPACE</p><h1>Keep your research together</h1><p>Sign in to collect evidence, write notes, compare passages and save cited briefs across devices.</p><p><Link href="/account">Sign in or create an account →</Link></p><p>Your recent inquiries remain saved in this browser.</p></section>;
  if (loading) return <p role="status">Opening your research workspace…</p>;
  return <><p className="eyebrow">RESEARCH WORKSPACE</p><h1>{state?.project.title ?? 'Organize a cited investigation'}</h1><p className="intro" dir="auto">{state?.project.question ?? 'Collect approved verification evidence, add researcher notes, and draft a cited brief.'}</p><p className="badge">Evidence, notes and briefs are saved to your research workspace</p>
    {error && <div className="error" role="alert">{error} <Link href="/sources">Check service availability</Link> · <Link href="/account">Account</Link></div>}<p role="status">{busy ? 'Working… completed work is preserved.' : status}</p>
    {!state ? <div className="project-grid"><section><h2>Projects</h2>{!projects.length && <p>No saved research projects yet.</p>}{projects.map(p => <article className="panel" key={p.id}><h3>{p.title}</h3><p dir="auto">{p.question}</p><button disabled={busy} onClick={() => void run(() => load(p.id))}>Open project</button></article>)}</section><section className="panel"><h2>Create project</h2><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run(async () => { const p = await researchRequest({ action: 'create', title: f.get('title'), question: f.get('question'), description: f.get('description'), resourceIds: f.getAll('resources'), languages: String(f.get('languages') ?? '').split(',').map(s => s.trim()).filter(Boolean) }); await load(p.id); }); }}><label>Title<input name="title" required maxLength={120} /></label><label>Research question<textarea dir="auto" name="question" required maxLength={2000} /></label><label>Description<textarea name="description" maxLength={4000} /></label><label>Languages (comma separated; empty means all)<input name="languages" placeholder="ar, en" /></label><fieldset><legend>Approved resources (none selected means all)</legend>{resources.map(r => <label className="check" key={r.id}><input name="resources" type="checkbox" value={r.id} />{r.title} · {r.language}</label>)}</fieldset><button disabled={busy}>Create project</button></form></section></div> : <>
      <button className="secondary" disabled={busy} onClick={() => void run(async () => { await load(); setState(undefined); setInputOpen(false); })}>All research projects</button>
      <details className="panel"><summary>Edit project details and scope</summary><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run(() => mutate({ action: 'update', title: f.get('title'), question: f.get('question'), description: f.get('description'), resourceIds: f.getAll('resources'), languages: String(f.get('languages')).split(',').map(s => s.trim()).filter(Boolean) })); }}><label>Title<input name="title" defaultValue={state.project.title} required maxLength={120} /></label><label>Research question<textarea name="question" defaultValue={state.project.question} required maxLength={2000} /></label><label>Description<textarea name="description" defaultValue={state.project.description} maxLength={4000} /></label><label>Languages<input name="languages" defaultValue={state.project.languages.join(', ')} /></label>{resources.map(r => <label className="check" key={r.id}><input type="checkbox" name="resources" value={r.id} defaultChecked={state.project.resourceIds.includes(r.id)} />{r.title}</label>)}<button disabled={busy}>Save details</button></form></details>
      <div className="actions" role="group" aria-label="Workspace views">{['Evidence', 'Notes', 'Brief'].map(t => <button key={t} aria-pressed={tab === t} className={tab === t ? '' : 'secondary'} onClick={() => setTab(t)}>{t}</button>)}</div>
      <p>{selected.length} passages selected</p>
      {tab === 'Evidence' && <><p>Submit text or a screenshot through the existing verification flow. Choose “Add to research project” on retrieved passages, then refresh here.</p><button disabled={busy} onClick={() => void run(async () => { const now = new Date().toISOString(); await ensureVerificationProject({ id: state.project.id, title: state.project.title, researchQuestion: state.project.question, createdAt: now, updatedAt: now }); setInputOpen(v => !v); })}>{inputOpen ? 'Close verification desk' : 'Submit material in this project'}</button>{inputOpen && <Workspace projectId={state.project.id} />}<button disabled={busy} onClick={() => void run(async () => { setState(await researchRequest(undefined, state.project.id)); })}>Refresh collected evidence</button><label>Filter evidence<input value={filter} onChange={e => setFilter(e.target.value)} /></label>{!state.evidence.length && <p>No saved evidence. Retrieve approved passages in the verification desk and add them to this project.</p>}
        {state.evidence.filter(e => `${e.source.title} ${e.snapshot.originalText} ${e.proposition}`.toLowerCase().includes(filter.toLowerCase())).map(e => <article className="panel" key={e.id}><label className="check"><input type="checkbox" checked={selected.includes(e.id)} disabled={busy} onChange={v => setSelected(s => v.target.checked ? [...s, e.id].slice(0, 8) : s.filter(id => id !== e.id))} />{e.source.title} · {e.snapshot.locator}</label>{!e.approved && <p className="error">Resource no longer approved; generation blocked when selected.</p>}<blockquote className="passage" dir="auto">{e.snapshot.originalText}</blockquote><p>Source text · {e.source.type === 'tafsir' ? 'Attributed scholarly interpretation' : e.source.type}</p><button className="secondary" onClick={() => setDetail(e)}>Inspect passage, claim and finding</button><form onSubmit={v => { v.preventDefault(); const f = new FormData(v.currentTarget); void run(() => mutate({ action: 'label', id: e.id, proposition: f.get('proposition'), relationship: f.get('relationship'), annotation: f.get('annotation') })); }}><label>Specific proposition<input name="proposition" defaultValue={e.proposition} maxLength={2000} /></label><label>Relationship ({e.labelAttribution})<select name="relationship" defaultValue={e.relationship}><option value="">Unset</option>{['supports', 'challenges', 'context', 'unclear'].map(r => <option key={r}>{r}</option>)}</select></label><label>Researcher annotation<textarea name="annotation" defaultValue={e.annotation} maxLength={10000} /></label><button disabled={busy}>Save relationship</button></form><button className="danger" disabled={busy} onClick={() => void run(async () => { await mutate({ action: 'removeEvidence', id: e.id }); setSelected(s => s.filter(id => id !== e.id)); })}>Remove project association</button></article>)}
        <button disabled={busy || selected.length < 2 || selected.length > 3} onClick={() => void run(() => mutate({ action: 'compare', selectedEvidenceIds: selected }))}>Compare selected passages (2–3)</button>{state.comparisons.map(d => <Document key={d.id} document={d} inspect={setDetail} />)}</>}
      {tab === 'Notes' && <><NoteEditor evidence={state.evidence} busy={busy} save={body => run(() => mutate(body))} />{state.notes.map(n => <NoteEditor key={n.id} note={n} evidence={state.evidence} busy={busy} save={body => run(() => mutate(body))} />)}</>}
      <div hidden={tab !== 'Brief'}><p>Generate from the selected evidence only. Researcher notes guide emphasis; they do not substantiate source claims.</p><button disabled={busy || !selected.length || !!state.briefs.length} onClick={() => void run(() => mutate({ action: 'brief', selectedEvidenceIds: selected }))}>Generate first brief ({selected.length} passages)</button>{!state.briefs.length && <p>No brief yet. Select evidence in the Evidence view.</p>}{state.briefs.map(d => <BriefEditor key={d.id} document={d} busy={busy} inspect={setDetail} save={content => run(() => mutate({ action: 'editBrief', id: d.id, statements: content }))} generate={content => run(async () => { await researchRequest({ action: 'editBrief', projectId: state.project.id, id: d.id, statements: content }); await mutate({ action: 'brief', selectedEvidenceIds: selected.length ? selected : d.selectedEvidenceIds }); })} />)}</div>
    </>}
    {detail && <section className="panel research-detail" aria-label="Original evidence detail"><button onClick={() => setDetail(undefined)}>Close passage detail</button><h2>{detail.source.title}</h2><p>{detail.source.author ?? 'Author unavailable'} · {detail.snapshot.edition} · {detail.snapshot.locator}</p><p>Translator: {detail.source.translator ?? detail.snapshot.translationIdentity ?? 'Not supplied'}</p><blockquote className="passage" dir="auto">{detail.snapshot.originalText}</blockquote><h3>Surrounding context</h3><p className="passage" dir="auto">{detail.snapshot.context || 'Context unavailable from provider.'}</p><a href={detail.snapshot.sourceUrl} target="_blank" rel="noopener noreferrer">Original source</a><p>Retrieved {new Date(detail.snapshot.retrievedAt).toLocaleString()} · Version {detail.snapshot.contentHash}</p><p>Approval: {detail.approved ? 'Approved' : 'Revoked or changed'}</p><h3>Associated proposition and verification finding</h3><p dir="auto">{detail.proposition}</p><p>Claim ID: {detail.claimId} · Revision: {detail.claimSnapshot?.revision ?? "Unavailable"}</p><blockquote dir="auto">{detail.claimSnapshot?.excerpt}</blockquote><p>{detail.claimSnapshot?.speaker} · {detail.claimSnapshot?.reference}</p><p>{detail.finding?.outcome ?? 'Finding unavailable'}</p><p>AI / deterministic finding: {detail.finding?.analysis?.explanation ?? detail.finding?.explanation}</p></section>}
  </>;
}
function NoteEditor({ note, evidence, busy, save }: { note?: ResearchNote; evidence: ResearchEvidence[]; busy: boolean; save: (body: Record<string, unknown>) => Promise<boolean> }) { return <form className="panel" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void save({ action: 'note', id: note?.id, content: f.get('content'), linkedEvidenceIds: f.getAll('links') }); }}><h3>{note ? 'Edit researcher note' : 'New researcher note'}</h3><p>Personal input, not verified source evidence.</p><label>Plain-text note<textarea name="content" dir="auto" required maxLength={10000} defaultValue={note?.content} /></label>{evidence.map(e => <label className="check" key={e.id}><input name="links" type="checkbox" value={e.id} defaultChecked={note?.linkedEvidenceIds.includes(e.id)} />{e.source.title} · {e.snapshot.locator}</label>)}<button disabled={busy}>Save note</button>{note && <button className="danger" type="button" disabled={busy} onClick={() => void save({ action: 'deleteNote', id: note.id })}>Delete note</button>}</form>; }
function Document({ document: d, inspect }: { document: ResearchDocument; inspect: (e: ResearchEvidence) => void }) { return <article className="panel"><h3>Revision {d.revision} · AI-generated analysis</h3><p>{d.model} · {d.promptVersion} · Source support needs researcher review</p>{d.citations.some(e => !e.approved) && <p className="error">Historical citation affected by revoked approval. Original record preserved.</p>}{d.statements.map((s, i) => <div key={i}><h4>{s.section}</h4><p dir="auto">{s.text}</p>{s.evidenceIds.map(id => { const citation = d.citations.find(e => e.id === id); return citation && <button className="secondary" key={id} onClick={() => inspect(citation)}>Source {d.citations.indexOf(citation) + 1}: {citation.source.title}</button>; })}</div>)}<h4>Source list</h4>{d.citations.map((e, i) => <p key={e.id}>[{i + 1}] {e.source.title} · {e.source.author} · {e.snapshot.edition} · {e.snapshot.locator} · {e.source.translator} · <a href={e.snapshot.sourceUrl}>{e.snapshot.sourceUrl}</a></p>)}</article>; }
function BriefEditor({ document: d, busy, inspect, save, generate }: { document: ResearchDocument; busy: boolean; inspect: (e: ResearchEvidence) => void; save: (s: Statement[]) => Promise<boolean>; generate: (s: Statement[]) => Promise<boolean> }) {
  const [content, setContent] = useState(d.statements), [dirty, setDirty] = useState(false), [message, setMessage] = useState('');
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  return <details className="panel" open><summary>Brief revision {d.revision}{dirty ? ' · Unsaved edits' : ''}</summary><Document document={{ ...d, statements: content }} inspect={inspect} />{content.map((s, i) => <label key={i}>{s.section} · Support needs review<textarea dir="auto" value={s.text} maxLength={4000} onChange={e => { setContent(c => c.map((v, n) => n === i ? { ...v, text: e.target.value, review: 'needs-review' } : v)); setDirty(true); }} /></label>)}<div className="actions"><button disabled={busy || !dirty} onClick={() => void save(content).then(ok => { if (ok) { setDirty(false); setMessage('Draft saved.'); } })}>Save draft</button><button disabled={busy} onClick={() => void generate(content).then(ok => { if (ok) setDirty(false); })}>Save draft and regenerate new revision</button><button disabled={busy} onClick={() => void navigator.clipboard.writeText(content.map(s => `${s.section}\n${s.text} ${s.evidenceIds.map(id => `[${d.citations.findIndex(e => e.id === id) + 1}]`).join(' ')}`).join('\n\n') + '\n\nSources\n' + d.citations.map((e, i) => `[${i + 1}] ${e.source.title}; ${e.source.author ?? ''}; ${e.snapshot.edition}; ${e.snapshot.locator}; translator: ${e.source.translator ?? 'not supplied'}; ${e.snapshot.sourceUrl}`).join('\n')).then(() => setMessage('Copied with source list.')).catch(() => setMessage('Clipboard unavailable.'))}>Copy with sources</button></div><p role="status">{message}</p></details>;
}
